@BASE_URL = http://localhost:8000/api/v1

###
GET {{BASE_URL}}/customers/ HTTP/1.1
Accept: "application/json"


###
GET {{BASE_URL}}/customers/1?includeInvoices=true HTTP/1.1
Accept: "application/json"

###
POST {{BASE_URL}}/customers HTTP/1.1
Accept: "application/json"
Content-Type: "application/json"

{
 "name" : "",
"type" : "i",
"email" : "pollos@gmail.com",
"address" : "New mexico ",
"city" : "New Mexico",
"state" : "Wyoming",
"postalCode" : "41768"
}

