@BASE_URL = http://localhost:8000/api/v1

###
GET {{BASE_URL}}/customers/ HTTP/1.1

###
GET {{BASE_URL}}/customers/1?includeInvoices=true HTTP/1.1

###
POST {{BASE_URL}}/customers HTTP/1.1
Accept: "application/json"
Content-Type: "application/json"

{
 "name" : "",
"type" : "i",
"email" : "pollos@gmail.com",
"address" : "New mexico ",
"city" : "New Mexico",
"state" : "Wyoming",
"postalCode" : "41768"
}

###
POST {{BASE_URL}}/invoices/bulkStore HTTP/1.1
Accept: "application/json"
Content-Type: "application/json"

[
    {
       "customerId" : 1,
        "amount"  : 8000,
        "status" : "P",
        "billedDate" : "2021-04-23 14:29:49",
        "paidDate" : null
    },
    {
        "customerId" : 1,
        "amount"  : 16000,
        "status" : "V",
        "billedDate" : "2021-04-23 14:29:49",
        "paidDate" : "2021-05-10 02:29:49"
    }
]